/**
 * QEP Moonshot Command Center — exec-packet-generator (Slice 6)
 *
 * Assembles a role-specific executive packet (markdown + structured JSON)
 * by reading the same data plumbing the live page uses, then writes a
 * row to `exec_packet_runs` for audit + history.
 *
 * Differs from exec-summary-generator in that this is the "ship to the
 * board" artifact: full KPI scorecard, trend snapshots, alert backlog,
 * and contributing-row tables for each metric. The summary generator is
 * the live in-page strip; this is the export.
 *
 * Auth: owner JWT only. No cron path.
 */
import { createClient, type SupabaseClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

const ALLOWED_ORIGINS = [
  "https://qualityequipmentparts.netlify.app",
  "https://qep.blackrockai.co",
  "http://localhost:5173",
];

function corsHeaders(origin: string | null) {
  return {
    "Access-Control-Allow-Origin": origin && ALLOWED_ORIGINS.includes(origin) ? origin : "",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Vary": "Origin",
  };
}

interface RequestBody {
  role: "ceo" | "cfo" | "coo";
  preset?: string;
  board_ready?: boolean;
  branch_id?: string | null;
}

async function authorizeLeadership(req: Request, admin: SupabaseClient): Promise<{ ok: boolean; userId?: string; workspace?: string; role?: string }> {
  const auth = req.headers.get("authorization");
  if (!auth?.startsWith("Bearer ")) return { ok: false };
  try {
    const { data: userRes } = await admin.auth.getUser(auth.slice(7));
    const userId = userRes?.user?.id;
    if (!userId) return { ok: false };
    const { data: profile } = await admin.from("profiles").select("role, active_workspace_id").eq("id", userId).maybeSingle();
    if (!profile?.role || !["owner", "manager"].includes(profile.role)) return { ok: false };
    return { ok: true, userId, workspace: profile.active_workspace_id, role: profile.role };
  } catch {
    return { ok: false };
  }
}

function fmt(metricKey: string, value: number | null): string {
  if (value == null) return "—";
  if (metricKey.includes("_pct") || metricKey.includes("_rate")) return `${Number(value).toFixed(1)}%`;
  if (metricKey.includes("revenue") || metricKey.includes("margin_dollars") || metricKey.includes("contribution") || metricKey.includes("pipeline") || metricKey.includes("exposure") || metricKey.includes("collected")) {
    return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 }).format(Number(value));
  }
  return Math.round(Number(value)).toString();
}

function evaluateBand(value: number | null, config: Record<string, unknown>): "good" | "warn" | "critical" | "neutral" {
  if (value == null) return "neutral";
  if (typeof config.critical_above === "number" && value >= config.critical_above) return "critical";
  if (typeof config.warn_above === "number" && value >= config.warn_above) return "warn";
  if (typeof config.critical_below === "number" && value <= config.critical_below) return "critical";
  if (typeof config.warn_below === "number" && value <= config.warn_below) return "warn";
  if (typeof config.warn_above === "number" || typeof config.warn_below === "number") return "good";
  return "neutral";
}

function buildPacket(
  role: string,
  definitions: Array<{ metric_key: string; label: string; description: string | null; formula_text: string; threshold_config: Record<string, unknown>; }>,
  snapByKey: Map<string, { metric_value: number | null; calculated_at: string; metadata: Record<string, unknown>; }>,
  alerts: Array<{ severity: string; title: string; description: string | null; metric_key: string | null; created_at: string; branch_id?: string | null }>,
  options: { preset?: string; boardReady?: boolean; branchLabel?: string | null; branchSnapshot?: Record<string, unknown> | null },
): { markdown: string; json: Record<string, unknown> } {
  const roleLabel = role === "ceo" ? "Chief Executive" : role === "cfo" ? "Chief Financial" : "Chief Operating";
  const dateStr = new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [];
  lines.push(`# ${roleLabel} Officer — Executive Packet`);
  lines.push(`### ${dateStr}`);
  lines.push("");
  lines.push("Generated by QEP Command Center. Every number below is registry-backed and links to a drillable source row.");
  if (options.preset) {
    lines.push(`Preset: ${options.preset}`);
  }
  if (options.branchLabel) {
    lines.push(`Branch focus: ${options.branchLabel}`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  if (options.boardReady) {
    lines.push("## Board-ready summary");
    lines.push("");
    const criticalCount = alerts.filter((alert) => alert.severity === "critical" || alert.severity === "error").length;
    lines.push(`- Open executive alerts: ${alerts.length}`);
    lines.push(`- Urgent issues: ${criticalCount}`);
    if (options.branchLabel) {
      lines.push(`- Branch focus: ${options.branchLabel}`);
    }
    lines.push(`- KPI coverage: ${definitions.length} tracked metrics in this packet`);
    lines.push("");
  }

  // Section 1: Headline scorecard
  lines.push("## 1. Scorecard");
  lines.push("");
  lines.push("| Metric | Value | Band | Last refresh |");
  lines.push("|---|---:|---|---|");
  for (const def of definitions) {
    const snap = snapByKey.get(def.metric_key);
    const value = snap?.metric_value ?? null;
    const band = evaluateBand(value, def.threshold_config ?? {});
    const bandIcon = band === "critical" ? "🔴 critical" : band === "warn" ? "🟡 warn" : band === "good" ? "🟢 good" : "⚪ no-data";
    const refresh = snap?.calculated_at ? new Date(snap.calculated_at).toLocaleString() : "never";
    lines.push(`| ${def.label} | ${fmt(def.metric_key, value)} | ${bandIcon} | ${refresh} |`);
  }
  lines.push("");

  // Section 2: Critical alerts
  const criticals = alerts.filter((a) => a.severity === "critical");
  const errors = alerts.filter((a) => a.severity === "error");
  const warns = alerts.filter((a) => a.severity === "warn");

  if (criticals.length > 0) {
    lines.push("## 2. Critical alerts (action required)");
    lines.push("");
    for (const a of criticals) {
      lines.push(`- 🔴 **${a.title}**${a.metric_key ? ` _(${a.metric_key})_` : ""}`);
      if (a.description) lines.push(`  - ${a.description}`);
    }
    lines.push("");
  }

  if (errors.length > 0) {
    lines.push("## 3. Errors");
    lines.push("");
    for (const a of errors) {
      lines.push(`- 🟠 ${a.title}`);
    }
    lines.push("");
  }

  if (warns.length > 0) {
    lines.push("## 4. Watch list");
    lines.push("");
    for (const a of warns) {
      lines.push(`- 🟡 ${a.title}`);
    }
    lines.push("");
  }

  if (options.branchSnapshot) {
    lines.push("## Branch focus");
    lines.push("");
    const branch = options.branchSnapshot as Record<string, unknown>;
    lines.push(`- Branch: ${options.branchLabel ?? "Unknown branch"}`);
    lines.push(`- Active work: ${branch.active ?? 0}`);
    lines.push(`- Closed work: ${branch.closed ?? 0}`);
    lines.push(`- Overdue work: ${branch.overdue ?? 0}`);
    lines.push("");
  }

  // Section: formulas appendix
  lines.push("## Appendix — Metric formulas");
  lines.push("");
  for (const def of definitions) {
    lines.push(`**${def.label}** (\`${def.metric_key}\`)`);
    if (def.description) lines.push(`  ${def.description}`);
    lines.push(`  Formula: \`${def.formula_text}\``);
    lines.push("");
  }

  lines.push("---");
  lines.push(`_Generated ${new Date().toISOString()}_`);

  // JSON sidecar — frozen snapshot of every datum the markdown references
  const json: Record<string, unknown> = {
    role,
    preset: options.preset ?? null,
    board_ready: options.boardReady ?? false,
    branch_label: options.branchLabel ?? null,
    branch_snapshot: options.branchSnapshot ?? null,
    generated_at: new Date().toISOString(),
    metrics: definitions.map((def) => {
      const snap = snapByKey.get(def.metric_key);
      return {
        metric_key: def.metric_key,
        label: def.label,
        value: snap?.metric_value ?? null,
        calculated_at: snap?.calculated_at ?? null,
        metadata: snap?.metadata ?? null,
        band: evaluateBand(snap?.metric_value ?? null, def.threshold_config ?? {}),
      };
    }),
    alerts: alerts.map((a) => ({
      severity: a.severity,
      title: a.title,
      description: a.description,
      metric_key: a.metric_key,
      created_at: a.created_at,
    })),
  };

  return { markdown: lines.join("\n"), json };
}

Deno.serve(async (req: Request) => {
  const origin = req.headers.get("origin");
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders(origin) });

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, { auth: { persistSession: false } });
  const auth = await authorizeLeadership(req, admin);
  if (!auth.ok) {
    return new Response(JSON.stringify({ error: "unauthorized" }), {
      status: 401,
      headers: { ...corsHeaders(origin), "Content-Type": "application/json" },
    });
  }

  let body: RequestBody;
  try { body = await req.json(); } catch {
    return new Response(JSON.stringify({ error: "invalid_json" }), { status: 400, headers: { ...corsHeaders(origin), "Content-Type": "application/json" } });
  }
  if (!body.role || !["ceo", "cfo", "coo"].includes(body.role)) {
    return new Response(JSON.stringify({ error: "invalid_role" }), { status: 400, headers: { ...corsHeaders(origin), "Content-Type": "application/json" } });
  }

  const workspace = auth.workspace ?? "default";

  try {
    let branchLabel: string | null = null;
    let branchSnapshot: Record<string, unknown> | null = null;
    if (body.branch_id) {
      const { data: branch } = await admin
        .from("branches")
        .select("slug, display_name")
        .eq("workspace_id", workspace)
        .eq("slug", body.branch_id)
        .maybeSingle();
      branchLabel = (branch as { display_name?: string | null })?.display_name ?? body.branch_id;

      const { data: branchRows } = await admin
        .from("exec_branch_comparison")
        .select("branch_id, overdue, active, closed")
        .eq("workspace_id", workspace)
        .eq("branch_id", body.branch_id)
        .limit(1);
      branchSnapshot = (branchRows?.[0] as Record<string, unknown> | undefined) ?? null;
    }

    const { data: defs } = await admin
      .from("analytics_metric_definitions")
      .select("metric_key, label, description, formula_text, threshold_config")
      .eq("owner_role", body.role)
      .eq("enabled", true);

    const definitions = (defs ?? []) as Array<{ metric_key: string; label: string; description: string | null; formula_text: string; threshold_config: Record<string, unknown>; }>;
    const metricKeys = definitions.map((d) => d.metric_key);

    const { data: snaps } = await admin
      .from("analytics_kpi_snapshots")
      .select("metric_key, metric_value, calculated_at, metadata")
      .eq("workspace_id", workspace)
      .in("metric_key", metricKeys.length > 0 ? metricKeys : ["__none__"])
      .in("refresh_state", ["fresh", "partial", "recalculated"])
      .order("calculated_at", { ascending: false });

    const snapByKey = new Map<string, { metric_value: number | null; calculated_at: string; metadata: Record<string, unknown>; }>();
    for (const s of (snaps ?? []) as Array<{ metric_key: string; metric_value: number | null; calculated_at: string; metadata: Record<string, unknown>; }>) {
      if (!snapByKey.has(s.metric_key)) snapByKey.set(s.metric_key, s);
    }

    const { data: alerts } = await admin
      .from("analytics_alerts")
      .select("severity, title, description, metric_key, created_at")
      .eq("workspace_id", workspace)
      .eq("role_target", body.role)
      .in("status", ["new", "acknowledged", "in_progress"])
      .order("created_at", { ascending: false });

    const { markdown, json } = buildPacket(
      body.role,
      definitions,
      snapByKey,
      (alerts ?? []) as Array<{ severity: string; title: string; description: string | null; metric_key: string | null; created_at: string; branch_id?: string | null }>,
      {
        preset: body.preset,
        boardReady: body.board_ready === true,
        branchLabel,
        branchSnapshot,
      },
    );

    // Persist run
    const { data: run, error: insErr } = await admin.from("exec_packet_runs").insert({
      workspace_id: workspace,
      role: body.role,
      generated_by: auth.userId,
      packet_md: markdown,
      packet_json: json,
      metrics_count: definitions.length,
      alerts_count: alerts?.length ?? 0,
      delivery_status: "generated",
      delivery_target: body.branch_id ?? null,
      metadata: {
        preset: body.preset ?? null,
        board_ready: body.board_ready === true,
        branch_id: body.branch_id ?? null,
        branch_label: branchLabel,
        generated_by_role: auth.role ?? null,
      },
    }).select("id, generated_at").maybeSingle();
    if (insErr) console.warn("[exec-packet-generator] persist failed:", insErr.message);

    // Audit log
    try {
      await admin.from("analytics_action_log").insert({
        workspace_id: workspace,
        user_id: auth.userId,
        action_type: "packet_generate",
        source_widget: "exec-packet-generator",
        metadata: { role: body.role, run_id: run?.id ?? null, metrics_count: definitions.length },
      });
    } catch { /* swallow */ }

    return new Response(JSON.stringify({
      ok: true,
      run_id: run?.id ?? null,
      role: body.role,
      generated_at: run?.generated_at ?? new Date().toISOString(),
      markdown,
      json,
      stats: { definitions: definitions.length, snapshots: snapByKey.size, alerts: alerts?.length ?? 0 },
    }), {
      status: 200,
      headers: { ...corsHeaders(origin), "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("[exec-packet-generator] error:", err);
    return new Response(JSON.stringify({ ok: false, error: (err as Error).message }), {
      status: 500,
      headers: { ...corsHeaders(origin), "Content-Type": "application/json" },
    });
  }
});
