import { describe, expect, it } from "vitest";

import { buildQuoteWizardStepRouterProps } from "../../lib/build-quote-wizard-step-router-props";
import type { QuoteWizardStepRouterProps } from "../../wizard/QuoteWizardStepRouter";

describe("buildQuoteWizardStepRouterProps", () => {
  it("merges grouped props into a single router props object", () => {
    const intake = {
      aiPrompt: "test",
      setAiPrompt: () => {},
      intakeRecorderOpen: false,
      setIntakeRecorderOpen: () => {},
      onVoiceRecorded: async () => {},
      voiceMutationPending: false,
      onBuildWithAi: () => {},
      aiIntakeMutationPending: false,
      aiIntakeMessage: null,
    } satisfies Pick<QuoteWizardStepRouterProps, keyof typeof intake>;

    const props = buildQuoteWizardStepRouterProps({
      intake,
      intelligence: {
        winProbContext: null,
        factorVerdicts: [],
        shadowHistory: [],
        shadowCalibration: null,
        intelligencePanel: null,
      },
      catalog: {
        setAvailableOptions: () => {},
        setAvailableOptionsLabel: () => {},
        availableOptionsLabel: null,
        configureTab: "attachment",
        setConfigureTab: () => {},
        availableOptions: [],
        setPackageItemSearchOpen: () => {},
        customLineTitle: "",
        setCustomLineTitle: () => {},
        customLinePrice: 0,
        setCustomLinePrice: () => {},
        addConfigLine: () => {},
      },
      availability: {
        equipmentKeyForLine: () => "",
        availabilityStatusForLine: () => null,
        availabilityRequestIdForLine: () => null,
        availabilityRequestCreatedAtForLine: () => null,
        availabilityRequestLabel: () => "",
        availabilityLabel: () => "",
        liveAvailabilityRequestForLine: () => null,
        liveAvailabilityStatusForLine: () => null,
        markAvailabilityConfirmationRequested: () => {},
        markAllAvailabilityConfirmationRequested: () => {},
        availabilityRequestMutationPending: false,
        sourceRequiredAwaitingConfirmation: [],
        sourceRequiredUnavailable: [],
        equipmentCanContinue: true,
        availabilityAwaitingCount: 0,
      },
      trade: {
        appliedValuationSnapshot: null,
        onPointShootApply: () => {},
        tradeChecklist: {},
        tradeCapture: {},
        tradeManagerApprovalRequired: false,
        onOpenTradeCapture: () => {},
      },
      totals: {
        equipmentTotal: 0,
        attachmentTotal: 0,
        internalCostLoadTotal: 0,
        pricingLineTotal: 0,
        subtotal: 0,
        discountTotal: 0,
        taxableBasis: 0,
        taxTotal: 0,
        customerTotal: 0,
        marginPct: 0,
        marginFloorPct: 10,
        marginFloorResolved: true,
        dealerCost: 0,
        netTotal: 0,
        marginAmount: 0,
        inboundFreightEligible: false,
      },
      pricing: {
        pricingLine: () => null,
        upsertPricingLine: () => {},
        discountLine: null,
        miscChargeTitle: "",
        setMiscChargeTitle: () => {},
        miscChargeAmount: 0,
        setMiscChargeAmount: () => {},
        miscCreditTitle: "",
        setMiscCreditTitle: () => {},
        miscCreditAmount: 0,
        setMiscCreditAmount: () => {},
        onAddMiscPricingLine: () => {},
        taxProfiles: [],
      },
      taxFinance: {
        taxPreviewData: undefined,
        taxPreviewLoading: false,
        taxPreviewError: false,
        branchStateProvince: undefined,
        activeQuotePackageId: null,
        allFinanceScenarios: [],
        cashDown: 0,
        amountFinanced: 0,
        financingPreviewLoading: false,
        financingPreviewError: false,
        leaseQuotingEnabled: false,
        branchDisplayName: "Missing",
        financeMethodLabel: "Cash",
      },
      approval: {
        sendReadiness: { ready: false, blockers: [] },
        requiresManagerApproval: false,
        userRole: null,
        canSubmitForApproval: false,
        approvalPending: false,
        approvalGranted: false,
        bypassApprovedWithoutCase: false,
        submitApprovalPending: false,
        onSubmitApproval: () => {},
        submitApprovalData: undefined,
        quoteStatus: "draft",
        onQuoteStatusChange: () => {},
        quoteTitle: "New quote",
        approvalCaseCanSend: false,
        approvalBlocker: null,
      },
      documentSend: {
        documentPersistenceLabel: "Not generated",
        documentFallbackGeneratedAt: null,
        documentArtifact: null,
        customerFacingDocumentBlocker: null,
        pdfGenerating: false,
        quoteMediaSnapshotLoading: false,
        documentActionError: null,
        documentReady: false,
        onGenerateDocument: () => {},
        taxResolved: true,
        taxResolutionBlocker: null,
        whyThisMachineRequired: false,
        whyThisMachineBlocker: null,
        previewReadiness: { ready: false, blockers: [] },
        emailReadiness: { ready: false, blockers: [] },
        textReadiness: { ready: false, blockers: [] },
        textQuoteEnabled: false,
        deliveryActionBusy: null,
        deliveryActionMessage: null,
        deliveryActionError: null,
        savePending: false,
        onPreview: () => {},
        onEmail: () => {},
        onText: () => {},
        onSaveFollowUp: () => {},
      },
    });

    expect(props.aiPrompt).toBe("test");
    expect(props.quoteTitle).toBe("New quote");
  });
});
