-- ============================================================================
-- Migration 185: Wave 6.11 — Flare in-app context-aware bug capture
--
-- See WAVE-6.11-FLARE-BUILD-SPEC.md (repo root) for the full contract.
--
-- Reconciliation notes vs the spec:
--   - Spec called for migration 167; that slot is taken by
--     quote_tax_and_incentives. Bumped to 185 (next free above the
--     parallel kb-discipline track at 183).
--   - Spec said `workspace_id uuid not null references workspaces(id)`.
--     The repo has no workspaces table — workspace_id is a text key
--     across the schema. Using `text` with the same default-via-helper
--     pattern as the rest of the migrations.
--   - Spec used pg_net + GUC settings for the fixed-notify trigger.
--     Replaced with a frontend-driven approach: when status flips,
--     the admin page calls the flare-notify-fixed edge fn directly.
--     No GUC dependency, no pg_net dependency.
-- ============================================================================

-- ── 1. flare_reports — system of record ──────────────────────────────────

create table if not exists public.flare_reports (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null default public.get_my_workspace(),
  reporter_id uuid references public.profiles(id) on delete set null,
  reporter_email text,
  reporter_role text,
  reporter_iron_role text,

  severity text not null check (severity in ('blocker', 'bug', 'annoyance', 'idea')),
  user_description text not null check (char_length(user_description) between 1 and 2000),

  -- Location
  url text not null,
  route text,
  page_title text,

  -- Captured context (all JSONB for flexibility)
  visible_entities jsonb not null default '[]'::jsonb,
  click_trail jsonb not null default '[]'::jsonb,
  network_trail jsonb not null default '[]'::jsonb,
  console_errors jsonb not null default '[]'::jsonb,
  route_trail jsonb not null default '[]'::jsonb,
  store_snapshot jsonb,
  react_query_cache_keys jsonb not null default '[]'::jsonb,
  feature_flags jsonb not null default '{}'::jsonb,

  -- Environment
  browser text,
  os text,
  viewport jsonb,           -- {width, height, dpr}
  network_type text,
  app_version text,
  git_sha text,
  build_timestamp timestamptz,

  -- Session
  session_id text,
  tab_id text,
  time_on_page_ms integer,
  performance_metrics jsonb,

  -- Storage artifacts
  screenshot_path text,
  dom_snapshot_path text,
  annotations jsonb not null default '[]'::jsonb,

  -- Phase F intelligence — auto-generated by flare-submit
  reproducer_steps text,                            -- markdown, derived from click_trail + route_trail
  ai_severity_recommendation text                   -- check (...) on insert
    check (ai_severity_recommendation is null or ai_severity_recommendation in
      ('blocker', 'bug', 'annoyance', 'idea')),
  ai_severity_reasoning text,
  ai_confidence numeric(3,2) check (ai_confidence is null or (ai_confidence >= 0 and ai_confidence <= 1)),
  hypothesis_pattern text,                          -- e.g. 'TypeError', 'NetworkError', 'RLS'
  linked_voice_capture_id uuid,                     -- if a voice capture was active
  recent_activity_id uuid,                          -- "what user was trying to do"

  -- Dispatch outcomes
  linear_issue_id text,
  linear_issue_url text,
  paperclip_issue_id text,
  paperclip_issue_url text,
  slack_ts text,
  exception_queue_id uuid,                          -- set if blocker → enqueue_exception
  dispatch_errors jsonb not null default '{}'::jsonb,

  -- Triage state
  status text not null default 'new'
    check (status in ('new', 'triaged', 'in_progress', 'fixed', 'wontfix', 'duplicate')),
  triaged_by uuid references public.profiles(id) on delete set null,
  triaged_at timestamptz,
  assigned_to uuid references public.profiles(id) on delete set null,
  resolution_notes text,
  duplicate_of uuid references public.flare_reports(id) on delete set null,
  fixed_at timestamptz,
  fix_deploy_sha text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

comment on table public.flare_reports is
  'Wave 6.11 Flare: in-app context-aware bug/idea reports. See WAVE-6.11-FLARE-BUILD-SPEC.md.';

-- Indexes per spec §7
create index idx_flare_workspace_status_created
  on public.flare_reports (workspace_id, status, created_at desc);

create index idx_flare_severity_open
  on public.flare_reports (workspace_id, severity)
  where status in ('new', 'triaged', 'in_progress');

create index idx_flare_reporter
  on public.flare_reports (reporter_id, created_at desc);

create index idx_flare_route_dedupe
  on public.flare_reports (workspace_id, route, created_at desc)
  where status != 'duplicate';

create index idx_flare_fixed_at
  on public.flare_reports (fixed_at desc)
  where status = 'fixed';

-- pg_trgm index for fuzzy dedupe over user_description (Phase F)
create index idx_flare_description_trgm
  on public.flare_reports using gin (user_description extensions.gin_trgm_ops);

-- ── 2. RLS ───────────────────────────────────────────────────────────────

alter table public.flare_reports enable row level security;

create policy "flare_workspace_read" on public.flare_reports for select
  using (workspace_id = public.get_my_workspace());

create policy "flare_insert_own" on public.flare_reports for insert
  with check (
    workspace_id = public.get_my_workspace()
    and reporter_id = auth.uid()
  );

create policy "flare_admin_update" on public.flare_reports for update
  using (
    workspace_id = public.get_my_workspace()
    and public.get_my_role() in ('owner', 'admin', 'manager')
  )
  with check (
    workspace_id = public.get_my_workspace()
    and public.get_my_role() in ('owner', 'admin', 'manager')
  );

create policy "flare_service_all" on public.flare_reports for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create trigger set_flare_reports_updated_at
  before update on public.flare_reports
  for each row execute function public.set_updated_at();

-- ── 3. Rate limit helper table ───────────────────────────────────────────

create table if not exists public.flare_rate_limits (
  reporter_id uuid not null,
  window_start timestamptz not null,
  count integer not null default 0,
  primary key (reporter_id, window_start)
);

create index idx_flare_rate_limits_cleanup on public.flare_rate_limits (window_start);

alter table public.flare_rate_limits enable row level security;

-- Service role only — the edge fn maintains this
create policy "flare_rate_limits_service" on public.flare_rate_limits for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ── 4. Phase F — fuzzy dedupe RPC ────────────────────────────────────────
-- Returns the count of similar flares in the last 7 days for the dedupe
-- chip in the drawer. Uses pg_trgm similarity on user_description AND
-- exact match on route as a stronger correlation signal.

create or replace function public.flare_dedupe_count(
  p_route text,
  p_description text,
  p_threshold numeric default 0.4
) returns integer
language plpgsql
security invoker
stable
as $$
declare
  v_count integer;
begin
  select count(*)::int into v_count
    from public.flare_reports f
    where f.workspace_id = public.get_my_workspace()
      and f.created_at > now() - interval '7 days'
      and f.status != 'duplicate'
      and (
        f.route = p_route
        or extensions.similarity(lower(f.user_description), lower(p_description)) >= p_threshold
      );
  return coalesce(v_count, 0);
end;
$$;

comment on function public.flare_dedupe_count(text, text, numeric) is
  'Wave 6.11 Phase F: fuzzy dedupe count over the last 7 days. Matches on exact route OR pg_trgm similarity ≥ threshold on user_description. Powers the "seen N times this week" chip in the drawer + admin queue.';

-- ── 5. Most-recent voice capture lookup (Phase F voice link) ─────────────
-- Returns the most recent voice_captures.id for the given user within
-- the last 5 minutes, or null. Used by flare-submit to auto-link.
-- Defensive: voice_captures may not be in every deployment.

create or replace function public.flare_recent_voice_capture(p_user_id uuid)
returns uuid
language plpgsql
security definer
stable
as $$
declare
  v_id uuid;
begin
  begin
    execute $q$
      select id from public.voice_captures
      where created_by = $1
        and created_at > now() - interval '5 minutes'
      order by created_at desc
      limit 1
    $q$ into v_id using p_user_id;
  exception when undefined_table then
    v_id := null;
  end;
  return v_id;
end;
$$;

comment on function public.flare_recent_voice_capture(uuid) is
  'Wave 6.11 Phase F: returns the user''s most recent voice_capture id from the last 5 minutes, or null. Wrapped in EXECUTE so deployments without voice_captures degrade gracefully.';

-- ── 6. Most-recent QRM activity lookup (Phase F autofill) ────────────────

create or replace function public.flare_recent_user_activity(p_user_id uuid)
returns json
language plpgsql
security definer
stable
as $$
declare
  v_row json;
begin
  begin
    execute $q$
      select json_build_object(
        'id', a.id,
        'type', a.activity_type,
        'subject', a.subject,
        'occurred_at', a.occurred_at
      )
      from public.qrm_activities a
      where a.created_by = $1
        and a.created_at > now() - interval '30 minutes'
      order by a.created_at desc
      limit 1
    $q$ into v_row using p_user_id;
  exception when others then
    v_row := null;
  end;
  return v_row;
end;
$$;

comment on function public.flare_recent_user_activity(uuid) is
  'Wave 6.11 Phase F: most recent qrm_activities row in the last 30 minutes for the user. Used by drawer autofill: "You were viewing/editing X — what went wrong?"';
