-- ============================================================
-- Migration 243: Sales Companion Foundation
-- Purpose: Tables, views, and RLS for the field-rep Sales Companion
-- ============================================================

-- ── TABLE: daily_briefings ──────────────────────────────────────────────────
-- Cache pre-generated AI briefings per rep per day.
-- Generated by scheduled Edge Function at 5am daily.
create table public.daily_briefings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  briefing_date date not null default current_date,
  briefing_content jsonb not null,
  -- Structure: {
  --   greeting: string,
  --   priority_actions: [{ type, customer_name, deal_id, summary }],
  --   expiring_quotes: [{ quote_id, customer_name, equipment, expires_at }],
  --   opportunities: [{ type, summary }],
  --   prep_cards: [{ customer_id, customer_name, meeting_time, fleet_summary, last_interaction, talking_points }],
  --   stats: { deals_in_pipeline, quotes_sent_this_week, total_pipeline_value }
  -- }
  generated_at timestamptz not null default now(),
  expires_at timestamptz not null default (current_date + interval '1 day'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_daily_briefings_user_date unique (user_id, briefing_date)
);

create index idx_daily_briefings_user_date on public.daily_briefings(user_id, briefing_date desc);
-- Justification: Primary lookup is always "get today's briefing for this rep"

alter table public.daily_briefings enable row level security;

create policy "daily_briefings_select_own" on public.daily_briefings
  for select using (user_id = auth.uid());

create policy "daily_briefings_service_all" on public.daily_briefings
  for all using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create trigger set_daily_briefings_updated_at
  before update on public.daily_briefings
  for each row execute function public.set_updated_at();

grant select on public.daily_briefings to authenticated;
grant all on public.daily_briefings to service_role;

-- ── TABLE: rep_preferences ──────────────────────────────────────────────────
-- Per-rep UI preferences (dark mode, default pipeline filter, notifications).
create table public.rep_preferences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade unique,
  dark_mode boolean not null default false,
  default_pipeline_filter text not null default 'all',
  notifications_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_rep_preferences_user on public.rep_preferences(user_id);
-- Justification: Always looked up by user_id on app load

alter table public.rep_preferences enable row level security;

create policy "rep_preferences_own" on public.rep_preferences
  for all using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "rep_preferences_service_all" on public.rep_preferences
  for all using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create trigger set_rep_preferences_updated_at
  before update on public.rep_preferences
  for each row execute function public.set_updated_at();

grant all on public.rep_preferences to authenticated;
grant all on public.rep_preferences to service_role;

-- ── TABLE: offline_sync_queue ────────────────────────────────────────────────
-- Stores actions captured offline, processed on reconnect.
create table public.offline_sync_queue (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  action_type text not null,
  -- 'log_visit' | 'advance_stage' | 'create_note' | 'schedule_followup'
  payload jsonb not null,
  queued_at timestamptz not null,
  synced_at timestamptz,
  sync_status text not null default 'pending',
  -- 'pending' | 'synced' | 'failed'
  error_message text,
  created_at timestamptz not null default now()
);

create index idx_offline_sync_queue_user_status on public.offline_sync_queue(user_id, sync_status);
-- Justification: On reconnect, fetch all pending actions for this user

alter table public.offline_sync_queue enable row level security;

create policy "offline_sync_queue_own" on public.offline_sync_queue
  for all using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "offline_sync_queue_service_all" on public.offline_sync_queue
  for all using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

grant all on public.offline_sync_queue to authenticated;
grant all on public.offline_sync_queue to service_role;

-- ── VIEW: v_rep_pipeline ─────────────────────────────────────────────────────
-- Simplified pipeline for Sales Companion.
-- Filters to authenticated rep's deals only via crm_rep_can_access_deal.
create or replace view public.v_rep_pipeline with (security_barrier = true) as
select
  d.id as deal_id,
  d.company_id,
  co.name as customer_name,
  ct.first_name || ' ' || ct.last_name as primary_contact_name,
  ct.phone as primary_contact_phone,
  s.name as stage,
  s.sort_order as stage_sort,
  d.amount,
  d.name as deal_name,
  d.created_at,
  d.updated_at,
  d.expected_close_on,
  d.last_activity_at,
  d.next_follow_up_at,
  extract(day from now() - d.last_activity_at) as days_since_activity,
  case
    when extract(day from now() - d.last_activity_at) > 14 then 'cold'
    when extract(day from now() - d.last_activity_at) > 7 then 'cooling'
    else 'warm'
  end as heat_status,
  d.deal_score
from public.crm_deals d
join public.crm_companies co on co.id = d.company_id
join public.crm_deal_stages s on s.id = d.stage_id
left join public.crm_contacts ct on ct.id = d.primary_contact_id
where d.deleted_at is null
  and d.assigned_rep_id = auth.uid()
  and d.closed_at is null
order by
  s.sort_order asc,
  d.last_activity_at desc nulls last;

grant select on public.v_rep_pipeline to authenticated;

-- ── VIEW: v_rep_customers ────────────────────────────────────────────────────
-- AI-ranked customer list for Sales Companion.
-- Surfaces customers who matter RIGHT NOW, not alphabetical.
create or replace view public.v_rep_customers with (security_barrier = true) as
select
  co.id as customer_id,
  co.name as company_name,
  ct.first_name || ' ' || ct.last_name as primary_contact_name,
  ct.phone as primary_contact_phone,
  ct.email as primary_contact_email,
  co.city,
  co.state,
  count(distinct d.id) filter (where d.closed_at is null and d.deleted_at is null) as open_deals,
  count(distinct q.id) filter (where q.status = 'linked' and q.deleted_at is null) as active_quotes,
  max(a.occurred_at) as last_interaction,
  extract(day from now() - max(a.occurred_at)) as days_since_contact,
  -- Opportunity score: higher = more urgent to contact
  (
    coalesce(count(distinct d.id) filter (where d.closed_at is null and d.deleted_at is null), 0) * 10 +
    case when max(a.occurred_at) < now() - interval '14 days' then 15 else 0 end +
    case when max(a.occurred_at) < now() - interval '30 days' then 20 else 0 end
  ) as opportunity_score
from public.crm_companies co
left join public.crm_contacts ct on ct.primary_company_id = co.id and ct.deleted_at is null
left join public.crm_deals d on d.company_id = co.id and d.assigned_rep_id = auth.uid()
left join public.quotes q on q.crm_deal_id = d.id and q.created_by = auth.uid()
left join public.crm_activities a on a.company_id = co.id and a.created_by = auth.uid()
where co.deleted_at is null
  and co.id in (
    select distinct company_id from public.crm_deals
    where assigned_rep_id = auth.uid() and deleted_at is null
    union
    select distinct company_id from public.crm_activities
    where created_by = auth.uid() and deleted_at is null and company_id is not null
  )
group by co.id, co.name, ct.id, ct.first_name, ct.last_name, ct.phone, ct.email, co.city, co.state
order by opportunity_score desc, last_interaction desc nulls last;

grant select on public.v_rep_customers to authenticated;

-- ── ROLLBACK ─────────────────────────────────────────────────────────────────
-- drop view if exists public.v_rep_customers;
-- drop view if exists public.v_rep_pipeline;
-- drop policy if exists "offline_sync_queue_service_all" on public.offline_sync_queue;
-- drop policy if exists "offline_sync_queue_own" on public.offline_sync_queue;
-- drop index if exists idx_offline_sync_queue_user_status;
-- drop table if exists public.offline_sync_queue;
-- drop policy if exists "rep_preferences_service_all" on public.rep_preferences;
-- drop policy if exists "rep_preferences_own" on public.rep_preferences;
-- drop trigger if exists set_rep_preferences_updated_at on public.rep_preferences;
-- drop index if exists idx_rep_preferences_user;
-- drop table if exists public.rep_preferences;
-- drop policy if exists "daily_briefings_service_all" on public.daily_briefings;
-- drop policy if exists "daily_briefings_select_own" on public.daily_briefings;
-- drop trigger if exists set_daily_briefings_updated_at on public.daily_briefings;
-- drop index if exists idx_daily_briefings_user_date;
-- drop table if exists public.daily_briefings;
