-- ============================================================================
-- Migration 280: Post-Sale Parts Playbooks (Slice 3.6)
--
-- When a QRM deal closes_won on equipment, Claude Sonnet 4.6 auto-generates
-- a 30/60/90-day parts maintenance plan grounded in:
--   - The sold equipment's make/model (crm_equipment)
--   - Machine profile's maintenance_schedule + common_wear_parts
--   - Customer pricing tier (from crm_companies if set)
--   - parts_catalog availability via match_parts_hybrid
--
-- The rep reviews, tweaks, then sends to customer. Every "sent" playbook
-- is a revenue forecast that we can close-loop against actual parts orders.
-- ============================================================================

create table if not exists public.post_sale_parts_playbooks (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null,
  deal_id uuid not null references public.qrm_deals(id) on delete cascade,
  equipment_id uuid references public.qrm_equipment(id) on delete set null,
  machine_profile_id uuid references public.machine_profiles(id) on delete set null,
  company_id uuid references public.qrm_companies(id) on delete set null,
  assigned_rep_id uuid references public.profiles(id),

  -- Structured playbook content. Shape:
  -- {
  --   windows: [
  --     {
  --       window: '30d' | '60d' | '90d',
  --       narrative: 'short rep-facing sentence',
  --       service_description: 'what service milestone this maps to',
  --       parts: [
  --         { part_number, description, qty, unit_price, total, probability, reason }
  --       ],
  --       total_revenue: numeric
  --     }
  --   ],
  --   grand_total_revenue: numeric,
  --   assumptions: { hours_per_day, customer_tier, etc. }
  -- }
  payload jsonb not null default '{}'::jsonb,

  total_revenue numeric(14,2) generated always as (
    coalesce((payload->>'grand_total_revenue')::numeric, 0)
  ) stored,

  status text not null default 'draft'
    check (status in ('draft', 'reviewed', 'sent', 'accepted', 'dismissed', 'expired')),

  generated_by text,          -- 'claude-sonnet-4-6' | 'manual' | 'cron'
  generation_batch_id text,
  tokens_in integer,
  tokens_out integer,

  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  sent_at timestamptz,
  sent_to_email text,
  accepted_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  unique (deal_id, equipment_id)
);

create index if not exists post_sale_playbooks_ws_status_idx
  on public.post_sale_parts_playbooks (workspace_id, status, created_at desc)
  where deleted_at is null;

create index if not exists post_sale_playbooks_rep_idx
  on public.post_sale_parts_playbooks (assigned_rep_id, status)
  where deleted_at is null;

alter table public.post_sale_parts_playbooks enable row level security;

-- Reps see their own playbooks; admin/manager/owner see all workspace ones.
drop policy if exists post_sale_playbooks_select on public.post_sale_parts_playbooks;
create policy post_sale_playbooks_select on public.post_sale_parts_playbooks
  for select
  using (
    deleted_at is null
    and (
      assigned_rep_id = auth.uid()
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid()
          and p.role in ('admin','manager','owner')
      )
    )
  );

-- Reps can update their own; admin/manager can update any.
drop policy if exists post_sale_playbooks_update on public.post_sale_parts_playbooks;
create policy post_sale_playbooks_update on public.post_sale_parts_playbooks
  for update
  using (
    deleted_at is null
    and (
      assigned_rep_id = auth.uid()
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid()
          and p.role in ('admin','manager','owner')
      )
    )
  );

comment on table public.post_sale_parts_playbooks is
  '30/60/90-day parts maintenance plans auto-generated by Claude when a deal closes_won on equipment. Rep reviews + sends. Source for forward parts revenue forecasting.';

-- ── RPC: post_sale_playbook_summary ─────────────────────────────────────────
-- Dashboard payload for PostSalePlaysPage. Counts + top drafts awaiting review.

create or replace function public.post_sale_playbook_summary(
  p_workspace text default null,
  p_limit integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  ws text;
  v_counts jsonb;
  v_drafts jsonb;
  v_revenue numeric;
begin
  if auth.uid() is not null then
    select active_workspace_id into ws from public.profiles where id = auth.uid();
    ws := coalesce(ws, 'default');
  else
    ws := coalesce(p_workspace, 'default');
  end if;

  begin
    select jsonb_build_object(
      'draft',     count(*) filter (where status = 'draft'),
      'reviewed',  count(*) filter (where status = 'reviewed'),
      'sent',      count(*) filter (where status = 'sent'),
      'accepted',  count(*) filter (where status = 'accepted'),
      'dismissed', count(*) filter (where status = 'dismissed'),
      'expired',   count(*) filter (where status = 'expired'),
      'total',     count(*)
    )
    into v_counts
    from public.post_sale_parts_playbooks
    where workspace_id = ws and deleted_at is null;
  exception when others then
    v_counts := jsonb_build_object(
      'draft', 0, 'reviewed', 0, 'sent', 0, 'accepted', 0,
      'dismissed', 0, 'expired', 0, 'total', 0);
  end;

  begin
    select coalesce(sum(total_revenue), 0)
    into v_revenue
    from public.post_sale_parts_playbooks
    where workspace_id = ws and deleted_at is null
      and status in ('draft', 'reviewed', 'sent');
  exception when others then v_revenue := 0; end;

  begin
    select coalesce(jsonb_agg(row_to_json(t) order by t.created_at desc), '[]'::jsonb)
    into v_drafts
    from (
      select
        pb.id, pb.deal_id, pb.equipment_id, pb.status, pb.total_revenue,
        pb.generated_by, pb.created_at, pb.sent_at,
        d.name as deal_name,
        co.name as company_name,
        eq.make, eq.model, eq.year,
        coalesce(p.full_name, p.email) as rep_name
      from public.post_sale_parts_playbooks pb
      left join public.qrm_deals d on d.id = pb.deal_id
      left join public.qrm_companies co on co.id = pb.company_id
      left join public.qrm_equipment eq on eq.id = pb.equipment_id
      left join public.profiles p on p.id = pb.assigned_rep_id
      where pb.workspace_id = ws and pb.deleted_at is null
      order by pb.created_at desc
      limit p_limit
    ) t;
  exception when others then v_drafts := '[]'::jsonb; end;

  return jsonb_build_object(
    'counts', v_counts,
    'open_revenue_usd', v_revenue,
    'recent', v_drafts,
    'generated_at', now()
  );
end;
$$;

grant execute on function public.post_sale_playbook_summary(text, integer) to authenticated;

-- ── RPC: eligible_deals_for_playbook ────────────────────────────────────────
-- Surfaces closed_won deals with equipment attached that don't already have
-- a playbook. Cron reads this to know which deals to generate for.

create or replace function public.eligible_deals_for_playbook(
  p_workspace text default null,
  p_limit integer default 20
)
returns table (
  deal_id uuid,
  workspace_id text,
  company_id uuid,
  assigned_rep_id uuid,
  equipment_id uuid,
  make text,
  model text,
  closed_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  ws text;
begin
  if auth.uid() is not null then
    select active_workspace_id into ws from public.profiles where id = auth.uid();
    ws := coalesce(ws, 'default');
  else
    ws := coalesce(p_workspace, 'default');
  end if;

  return query
  select distinct on (d.id, eq.id)
    d.id as deal_id,
    d.workspace_id,
    d.company_id,
    d.assigned_rep_id,
    eq.id as equipment_id,
    eq.make,
    eq.model,
    d.closed_at
  from public.qrm_deals d
  join public.qrm_deal_stages s on s.id = d.stage_id
  join public.qrm_deal_equipment cde on cde.deal_id = d.id
  join public.qrm_equipment eq on eq.id = cde.equipment_id
  where d.workspace_id = ws
    and d.deleted_at is null
    and s.is_closed_won = true
    and d.closed_at is not null
    and d.closed_at >= now() - interval '180 days'
    and eq.deleted_at is null
    and not exists (
      select 1 from public.post_sale_parts_playbooks pb
      where pb.deal_id = d.id
        and pb.equipment_id = eq.id
        and pb.deleted_at is null
    )
  order by d.id, eq.id, d.closed_at desc
  limit p_limit;
end;
$$;

grant execute on function public.eligible_deals_for_playbook(text, integer) to authenticated;

-- Auto-update updated_at.
drop trigger if exists post_sale_playbooks_set_updated_at on public.post_sale_parts_playbooks;
create trigger post_sale_playbooks_set_updated_at
  before update on public.post_sale_parts_playbooks
  for each row execute function public.set_updated_at();

-- ============================================================================
-- Migration 280 complete.
-- ============================================================================
