-- ============================================================================
-- Migration 315: Hub — changelog + morning briefing audience extension
--
-- Closes the Day 1-2 schema scaffold.
--
-- Two surfaces:
--
--   1. hub_changelog — a dedicated event stream fed by hub-changelog-from-commit
--      (a cron that scans [QEP-*] commits on main and synthesizes human-voice
--      summaries via Claude). Drives the /brief activity feed tile and the
--      "your fix shipped" completion of the stakeholder feedback loop.
--
--   2. morning_briefings.audience — a new column on the existing table. The
--      hub spec originally proposed a separate hub_daily_briefings table; on
--      review, the shape is identical to what's already in morning_briefings
--      (migration 055). Extending the existing table instead avoids a shadow
--      briefings system and means owner-morning-brief and stakeholder-morning-brief
--      share the same read path.
--
-- Design decisions (locked):
--   * Changelog is append-only. Updates are via new rows with change_type,
--     not mutations. Deletion is soft (deleted_at) for audit cleanliness.
--   * morning_briefings audience column is nullable on purpose — all existing
--     rows are internal; backfilling them isn't load-bearing and would churn
--     the unique(user_id, briefing_date) constraint.
-- ============================================================================

-- ── 1. hub_changelog ────────────────────────────────────────────────────────

create table if not exists public.hub_changelog (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null default public.get_my_workspace(),
  build_item_id uuid references public.hub_build_items(id) on delete set null,
  feedback_id uuid references public.hub_feedback(id) on delete set null,
  summary text not null,
  details text,
  change_type text not null check (change_type in (
    'shipped', 'updated', 'fixed', 'started'
  )),
  demo_url text,
  commit_sha text,
  notebooklm_source_id uuid references public.hub_knowledge_source(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

comment on table public.hub_changelog is
  'Stakeholder Build Hub: append-only event stream. Populated by '
  'hub-changelog-from-commit cron (every 15 min). Drives the /brief activity '
  'feed and completes the "your feedback shipped" loop via feedback_id link.';

comment on column public.hub_changelog.feedback_id is
  'If the change closed a feedback item, link it here. The /brief feedback '
  'thread surfaces this row as the "shipped" event.';

create index if not exists idx_hub_changelog_workspace_recent
  on public.hub_changelog (workspace_id, created_at desc)
  where deleted_at is null;

create index if not exists idx_hub_changelog_build_item
  on public.hub_changelog (build_item_id, created_at desc)
  where deleted_at is null and build_item_id is not null;

create index if not exists idx_hub_changelog_feedback
  on public.hub_changelog (feedback_id)
  where deleted_at is null and feedback_id is not null;

create index if not exists idx_hub_changelog_commit
  on public.hub_changelog (commit_sha)
  where deleted_at is null and commit_sha is not null;

alter table public.hub_changelog enable row level security;

create policy hub_changelog_service_all on public.hub_changelog
  for all to service_role using (true) with check (true);

create policy hub_changelog_workspace_read on public.hub_changelog
  for select
  using (
    workspace_id = public.get_my_workspace()
    and deleted_at is null
  );

-- Internal admin/owner can insert manually (for seeding + manual entries).
-- The cron path uses service_role and bypasses this policy.
create policy hub_changelog_admin_insert on public.hub_changelog
  for insert
  with check (
    workspace_id = public.get_my_workspace()
    and public.get_my_audience() = 'internal'
    and public.get_my_role() in ('admin', 'owner')
  );

grant select on public.hub_changelog to authenticated;
grant insert on public.hub_changelog to authenticated;

-- ── 2. morning_briefings.audience column ────────────────────────────────────
-- Extend the existing table (migration 055) instead of creating a parallel
-- hub_daily_briefings. Shape is identical; both internal and stakeholder
-- briefings share the same read path in the frontend.

alter table public.morning_briefings
  add column if not exists audience text
    check (audience is null or audience in ('internal', 'stakeholder'));

comment on column public.morning_briefings.audience is
  'Audience classification for the briefing. NULL = legacy (pre-hub, treated '
  'as internal). "internal" = generated by owner-morning-brief. "stakeholder" '
  '= generated by stakeholder-morning-brief for Ryan/Rylee/Juan/Angela.';

create index if not exists idx_morning_briefings_audience_date
  on public.morning_briefings (audience, briefing_date desc)
  where audience is not null;
