-- 496_crm_companies_view_wave2_refresh.sql
-- Refresh crm_companies compatibility view after qrm_companies Wave 2 columns.
-- The existing view order from Wave 0 is preserved and new columns are appended
-- to satisfy Phase-8 crm_companies naming without altering a view as a table.

create or replace view public.crm_companies
  with (security_invoker = true)
  as
  select
    id,
    workspace_id,
    name,
    parent_company_id,
    assigned_rep_id,
    hubspot_company_id,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    metadata,
    created_at,
    updated_at,
    deleted_at,
    legal_name,
    dba,
    phone,
    website,
    classification,
    territory_code,
    county,
    status,
    notes,
    search_1,
    search_2,
    public.mask_customer_ein(ein) as ein,
    (ein is not null and not public.qrm_can_access_customer_ein()) as ein_masked,
    product_category,
    industry,
    size,
    owner_name,
    brand_of_interest,
    township,
    lot,
    concession,
    latitude,
    longitude,
    business_fax,
    business_cell,
    business_email,
    tax_code_equipment,
    tax_code_parts,
    tax_code_service,
    tax_code_rental,
    labor_tax_code_1,
    labor_tax_code_2,
    exempt_status_notes,
    avatax_entity_use_code,
    duns_number,
    naics_code,
    opt_out_sale_pi,
    opt_out_sale_pi_at,
    opt_out_sale_pi_source,
    ar_type,
    combine_statement_with_parent,
    statement_message,
    statement_date,
    payment_terms_id,
    payment_terms_code,
    terms_code,
    default_po_number,
    default_po_expires_at,
    po_required_on_invoice,
    assess_late_charges,
    print_retail_price,
    print_parts_invoices,
    auto_email_inspection,
    ibe_account_number,
    credit_limit_cents,
    credit_limit_set_by,
    credit_limit_set_at,
    credit_limit_review_at,
    pricing_group_id,
    pricing_level,
    discount_group,
    preferred_language,
    home_branch_id,
    do_not_contact,
    notify_payment_issues,
    notify_multiple_accounts,
    notify_legal_concerns,
    notify_birthday,
    requires_hazmat_certified_carrier,
    requires_lift_gate,
    requires_signature,
    allow_after_hours_dropoff,
    preferred_carrier,
    shipping_notes,
    header_alert,
    primary_contact_id,
    ar_agency_id,
    total_ar_cents,
    total_ar_computed_at,
    responsible_branch_id,
    ar_type::text as ar_account_type,
    last_invoice_date,
    avg_payment_days,
    avg_payment_days_calculated_at,
    last_payment_date,
    highest_ar_balance,
    highest_ar_balance_date,
    (credit_limit_cents::numeric / 100.0) as credit_limit,
    'USD'::text as credit_limit_currency,
    credit_limit_review_at::timestamptz as credit_limit_review_at_ts,
    current_ar_balance,
    current_ar_balance_updated_at,
    credit_rating,
    credit_rating_source,
    credit_rating_updated_at
  from public.qrm_companies;

comment on view public.crm_companies is
  'CRM company compatibility view. Wave 2 appends IntelliDealer customer/AR columns from qrm_companies; EIN remains role-masked.';
