import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { withScratchPostgres, hasScratchPostgres } from "../../scripts/testing/scratch-postgres";
const migration = readFileSync(new URL('./841_service_operational_integrity.sql', import.meta.url), 'utf8');
const schema = `
create role anon; create role authenticated; create role service_role;
create schema auth;create schema storage;create table storage.objects(bucket_id text,name text);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.uid',true),'')::uuid$$;
create function auth.role() returns text language sql stable as $$select current_setting('request.role',true)$$;
create function get_my_workspace() returns text language sql stable as $$select current_setting('request.workspace',true)$$;
create function get_my_role() returns text language sql stable as $$select current_setting('request.qep_role',true)$$;
create type service_source_type as enum ('call'); create type service_request_type as enum ('repair','internal');
create type service_priority as enum ('normal'); create type service_status_flag as enum ('shop_job');
create table profiles(id uuid primary key); create table profile_workspaces(profile_id uuid,workspace_id text);
create table qrm_companies(id uuid primary key,workspace_id text,deleted_at timestamptz);
create table qrm_equipment(id uuid primary key default gen_random_uuid(),workspace_id text,name text not null,make text,model text,serial_number text,year int,company_id uuid not null references qrm_companies,category text,metadata jsonb,deleted_at timestamptz);
create table service_jobs(id uuid primary key default gen_random_uuid(),workspace_id text,customer_id uuid,machine_id uuid references qrm_equipment,source_type service_source_type,request_type service_request_type,priority service_priority,current_stage text,advisor_id uuid,technician_id uuid,customer_problem_summary text,haul_required boolean,shop_or_field text,hour_meter_reading numeric,odometer_miles numeric,machine_make text,machine_model text,machine_serial_number text,machine_year int,complaint text,cause text,correction text,promised_at timestamptz,field_site_location text,field_site_contact_name text,field_site_contact_phone text,field_site_conditions_access_notes text,selected_job_code_id uuid,status_flags service_status_flag[],estimate_authorization_required boolean,estimate_authorization_status text,estimate_reauth_threshold_pct numeric,closed_at timestamptz,comeback_no_rebill boolean,service_internal_work_class text,renter_fault_billable boolean,created_at timestamptz default now());
alter table service_jobs add column contact_id uuid,add column branch_id text,add column service_manager_id uuid,add column requested_by_name text,add column scheduled_start_at timestamptz,add column scheduled_end_at timestamptz,add column portal_request_id uuid,add column ai_diagnosis_summary text;
create table job_codes(id uuid,workspace_id text);create table qrm_contacts(id uuid,workspace_id text,deleted_at timestamptz);create table service_requests(id uuid,workspace_id text);
alter table service_jobs add column deleted_at timestamptz;
create table service_job_events(id uuid default gen_random_uuid(),workspace_id text,job_id uuid,event_type text,actor_id uuid,new_stage text,metadata jsonb);
create table service_job_segments(id uuid primary key default gen_random_uuid(),workspace_id text,service_job_id uuid,technician_id uuid,hours_actual numeric,segment_number int,description text,status text,deleted_at timestamptz);
create table service_job_segment_photos(workspace_id text,service_job_id uuid,service_job_segment_id uuid,phase text,category text,storage_bucket text,storage_path text,caption text,content_type text,uploaded_by uuid);
create table service_timecards(id uuid primary key,workspace_id text,service_job_id uuid,technician_id uuid,segment_id uuid,clocked_in_at timestamptz,clocked_out_at timestamptz,hours numeric generated always as (round(extract(epoch from(clocked_out_at-clocked_in_at))/3600,2)) stored);
create table service_haul_rate_sheets(id uuid primary key default gen_random_uuid(),workspace_id text,rate_type text,truck_class text,mileage_band_min numeric,mileage_band_max numeric,base_rate_cents bigint,per_mile_rate_cents bigint,round_trip_minimum_miles numeric,per_haul_minimum_cents bigint,effective_date date default current_date,expiration_date date,active boolean default true,notes text,created_at timestamptz default now(),updated_at timestamptz default now());
create table employees(id uuid,workspace_id text,profile_id uuid,deleted_at timestamptz);
create table service_labor_ledger(workspace_id text,service_job_id uuid,service_job_segment_id uuid,service_timecard_id uuid,employee_id uuid,technician_id uuid,labor_date date,started_at timestamptz,ended_at timestamptz,actual_hours numeric,source_system text,source_key text,notes text,deleted_at timestamptz);
create table service_quotes(id uuid primary key,workspace_id text not null default 'ws',job_id uuid not null references service_jobs(id),status text,version int);
create table service_quote_lines(id uuid primary key default gen_random_uuid(),workspace_id text not null default 'ws',quote_id uuid not null references service_quotes(id),payer_type text,line_type text,description text,quantity numeric,unit_price numeric,extended_price numeric,sort_order int);
create table portal_customers(id uuid primary key,crm_company_id uuid,workspace_id text);
create table customer_invoices(id uuid primary key default gen_random_uuid(),workspace_id text,portal_customer_id uuid,crm_company_id uuid,invoice_number text unique,invoice_date date,due_date date,description text,amount numeric,tax numeric,total numeric,status text,invoice_type text,service_job_id uuid,amount_paid numeric,created_at timestamptz default now(),quickbooks_gl_status text,quickbooks_gl_last_error text);
alter table customer_invoices add column native_signature_id uuid;
create table customer_invoice_line_items(id uuid primary key default gen_random_uuid(),workspace_id text,invoice_id uuid references customer_invoices,line_number int,description text check(description<>'FAIL'),quantity numeric,unit_price numeric,line_total numeric generated always as(quantity*unit_price) stored,finance_department text,finance_segment text,finance_category text,finance_classification_source text,finance_classified_at timestamptz);
create table quickbooks_gl_sync_jobs(workspace_id text,invoice_id uuid unique,source_type text,posting_mode text,status text);
create table service_agreement_programs(id uuid primary key,workspace_id text,name text,is_active boolean,is_provisional boolean,review_status text,deleted_at timestamptz);
create table service_agreements(id uuid primary key,workspace_id text,program_id uuid,program_name text,status text,deleted_at timestamptz);
create function service_plan_enroll_equipment(text,uuid,date,numeric,uuid) returns jsonb language plpgsql as $$begin if $4<0 then raise exception 'Invalid baseline';end if; return jsonb_build_object('enrolled',true);end$$;
alter table service_quotes enable row level security;alter table service_quote_lines enable row level security;
create policy quote_scope on service_quotes for all to authenticated using(workspace_id=get_my_workspace()) with check(workspace_id=get_my_workspace());
create policy line_scope on service_quote_lines for all to authenticated using(workspace_id=get_my_workspace()) with check(workspace_id=get_my_workspace());
grant select,insert,update on service_quotes,service_quote_lines to authenticated;
grant usage on schema public,auth to authenticated; grant select on service_haul_rate_sheets to authenticated;grant select,insert,update,delete on service_timecards to authenticated;
insert into profiles values ('10000000-0000-0000-0000-000000000001'),('10000000-0000-0000-0000-000000000002');
insert into profile_workspaces values ('10000000-0000-0000-0000-000000000001','ws');
insert into qrm_companies values ('20000000-0000-0000-0000-000000000001','ws',null);
`;
const operator = `set role authenticated;set request.role='authenticated';set request.uid='10000000-0000-0000-0000-000000000001';set request.workspace='ws';set request.qep_role='service_writer';`;
const jobId = '30000000-0000-0000-0000-000000000001';
const payload = JSON.stringify({ customer_id:'20000000-0000-0000-0000-000000000001',new_machine:{make:'Example',model:'M1',serial_number:'TEST-841',year:2025},source_type:'call',request_type:'repair',priority:'normal',shop_or_field:'shop',hour_meter_reading:10,complaint:'Leak',cause:'Pending diagnosis',correction:'Inspect',promised_at:'2026-09-08T12:00:00Z',status_flags:['shop_job'] });
(hasScratchPostgres ? describe : describe.skip)('service domain transactions', () => {
 it('persists first machine+job once, rejects mismatched replay, protects technician fields/clocks and rolls back invoice line failures', () => withScratchPostgres(query => {
  query(schema);query(migration);
  const create = `${operator} select service_create_intake('${jobId}','${payload}');`;
  expect(query(create)).toContain(jobId);expect(query(create)).toContain(jobId);
  expect(query('reset role;select count(*) from qrm_equipment;')).toEndWith('1');
  expect(() => query(`${operator}select service_create_intake('${jobId}','${payload.replace('Leak','Changed')}');`)).toThrow('Operation conflict');
  const badId='30000000-0000-0000-0000-000000000002';
  expect(() => query(`${operator}select service_create_intake('${badId}','${payload.replace('TEST-841','ROLLBACK').replace('"hour_meter_reading":10','"hour_meter_reading":-1')}');`)).toThrow('Invalid hour');
  expect(query('reset role;select count(*) from qrm_equipment;')).toEndWith('1');
  query(`reset role;update service_jobs set technician_id='10000000-0000-0000-0000-000000000001' where id='${jobId}';`);
  const tech=`${operator}set request.qep_role='technician';`;
  expect(query(`${tech}select service_record_field_packet('40000000-0000-0000-0000-000000000001','${jobId}','{"kind":"job_update","fields":{"hour_meter_reading":12},"base":{"hour_meter_reading":10}}');`)).toContain('12');
  expect(() => query(`${tech}select service_record_field_packet('40000000-0000-0000-0000-000000000002','${jobId}','{"kind":"job_update","fields":{"invoice_total":1}}');`)).toThrow('Protected field');
  expect(() => query(`${tech}select service_record_field_packet('40000000-0000-0000-0000-000000000003','${jobId}','{"kind":"job_update","fields":{"hour_meter_reading":13},"base":{"hour_meter_reading":10}}');`)).toThrow('Conflict');
  expect(() => query(`${tech}set request.uid='10000000-0000-0000-0000-000000000002';select service_record_field_packet('40000000-0000-0000-0000-000000000004','${jobId}','{"kind":"job_update","fields":{"cause":"Other"}}');`)).toThrow('not assigned');
  expect(query(`${tech}select service_machine_history('${jobId}');`)).toContain('Leak');
  expect(() => query(`${tech}set request.uid='10000000-0000-0000-0000-000000000002';select service_machine_history('${jobId}');`)).toThrow('not assigned');
  expect(() => query(`${tech}select service_record_field_packet('40000000-0000-0000-0000-000000000009','${jobId}','{"kind":"job_update","captured_by":"10000000-0000-0000-0000-000000000002","fields":{"cause":"X"}}');`)).toThrow('different operator');
  const start=`${tech}select service_record_field_packet('40000000-0000-0000-0000-000000000005','${jobId}','{"kind":"clock_start","session_id":"50000000-0000-0000-0000-000000000001","occurred_at":"2026-01-01T10:00:00Z"}');`;
  query(start);query(start);
  expect(() => query(`${tech}update service_timecards set clocked_in_at='2026-01-01T09:00:00Z';`)).toThrow('immutable');
  const stop=`${tech}select service_record_field_packet('40000000-0000-0000-0000-000000000006','${jobId}','{"kind":"clock_stop","session_id":"50000000-0000-0000-0000-000000000001","occurred_at":"2026-01-01T11:00:00Z"}');`;
  query(stop);query(stop);expect(query("reset role;select count(*) from service_labor_ledger where actual_hours=1;")).toEndWith('1');expect(query('reset role;select count(*) || \':\' || sum(hours) from service_timecards;')).toEndWith('1:1.00');
  query(`reset role;insert into service_quotes(id,job_id,status,version) values('60000000-0000-0000-0000-000000000001','${jobId}','approved',1);insert into service_quote_lines(quote_id,payer_type,line_type,description,quantity,unit_price,extended_price,sort_order) values('60000000-0000-0000-0000-000000000001','customer','part','FAIL',1,100,100,1);`);
  expect(() => query(`${operator}select service_generate_invoice_atomic('${jobId}');`)).toThrow('check constraint');
  expect(query('reset role;select count(*) from customer_invoices;')).toEndWith('0');
  query("reset role;update service_quote_lines set description='Part';");
  query(`${operator}select service_generate_invoice_atomic('${jobId}');`);query(`${operator}select service_generate_invoice_atomic('${jobId}');`);
  expect(query('reset role;select count(*) from customer_invoices;')).toEndWith('1');
  expect(query("reset role;select finance_department from customer_invoice_line_items;")).toEndWith('parts');
  query("reset role;update service_quote_lines set line_type='labor';");
  query(`${operator}select service_generate_invoice_atomic('${jobId}');`);
  expect(query("reset role;select finance_department from customer_invoice_line_items;")).toEndWith('service');
  query("reset role;update customer_invoices set status='sent';update service_quote_lines set line_type='part';");
  expect(() => query(`${operator}select service_generate_invoice_atomic('${jobId}');`)).toThrow('content/classification');
  query(`reset role;update service_jobs set technician_id=null where id='${jobId}';update service_job_segments set technician_id='10000000-0000-0000-0000-000000000001',deleted_at=now() where service_job_id='${jobId}';`);
  expect(() => query(`${tech}select service_machine_history('${jobId}');`)).toThrow('not assigned');
  expect(() => query(`${tech}select service_record_field_packet('40000000-0000-0000-0000-000000000001','${jobId}','{"kind":"job_update","fields":{"hour_meter_reading":12},"base":{"hour_meter_reading":10}}');`)).toThrow('not assigned');
  query(`reset role;update service_jobs set deleted_at=now(),technician_id='10000000-0000-0000-0000-000000000001' where id='${jobId}';`);
  expect(() => query(`${tech}select service_machine_history('${jobId}');`)).toThrow('Job not found');

  expect(query(`${operator}select total_cents from service_calculate_haul_charge('ws','flatbed_tilt_deck',10,'internal');`)).toEndWith('7500');
  expect(() => query(`${operator}select * from service_calculate_haul_charge('ws','unconfigured',10,'customer');`)).toThrow('No approved haul rate');
  query(`reset role;insert into service_agreement_programs values('70000000-0000-0000-0000-000000000001','ws','Approved plan',true,false,'reviewed',null);insert into service_agreements values('80000000-0000-0000-0000-000000000001','ws',null,'Draft','draft',null);`);
  expect(() => query(`${operator}set request.qep_role='manager';select service_enroll_agreement('80000000-0000-0000-0000-000000000001','70000000-0000-0000-0000-000000000001','2026-09-06',-1);`)).toThrow('Invalid baseline');
  expect(query('reset role;select status from service_agreements;')).toEndWith('draft');

 }), 30_000);

 it('ignores legacy foreign-workspace source rows and rejects newly mismatched parent references',()=>withScratchPostgres(query=>{
  query(schema);
  query(`insert into qrm_companies values('20000000-0000-0000-0000-000000000008','other',null);
    insert into service_jobs(id,workspace_id,customer_id) values('30000000-0000-0000-0000-000000000008','other','20000000-0000-0000-0000-000000000008');
    insert into service_quotes(id,workspace_id,job_id,status,version) values('60000000-0000-0000-0000-000000000008','other','30000000-0000-0000-0000-000000000008','approved',1);
    insert into service_quote_lines(workspace_id,quote_id,payer_type,line_type,description,quantity,unit_price,extended_price,sort_order) values('other','60000000-0000-0000-0000-000000000008','customer','part','Legitimate part',1,50,50,1);`);
  query(`${operator}insert into service_quotes(id,workspace_id,job_id,status,version) values('60000000-0000-0000-0000-000000000009','ws','30000000-0000-0000-0000-000000000008','approved',99);
    insert into service_quote_lines(workspace_id,quote_id,payer_type,line_type,description,quantity,unit_price,extended_price,sort_order) values('ws','60000000-0000-0000-0000-000000000009','customer','labor','Foreign poison',1,999,999,1);
    insert into service_quote_lines(workspace_id,quote_id,payer_type,line_type,description,quantity,unit_price,extended_price,sort_order) values('ws','60000000-0000-0000-0000-000000000008','customer','labor','Foreign line',1,888,888,2);reset role;`);
  query(migration);
  query(`${operator}set request.workspace='other';set request.uid='10000000-0000-0000-0000-000000000002';select service_generate_invoice_atomic('30000000-0000-0000-0000-000000000008');`);
  expect(query("reset role;select total from customer_invoices where workspace_id='other';")).toEndWith('50');
  expect(query("reset role;select description from customer_invoice_line_items where workspace_id='other';")).toEndWith('Legitimate part');
  expect(()=>query(`${operator}insert into service_quotes(id,workspace_id,job_id,status,version) values(gen_random_uuid(),'ws','30000000-0000-0000-0000-000000000008','approved',100);`)).toThrow('service_quotes_job_workspace_841');
  expect(()=>query(`${operator}insert into service_quote_lines(workspace_id,quote_id,payer_type,line_type,description,quantity,unit_price,extended_price) values('ws','60000000-0000-0000-0000-000000000008','customer','part','Rejected',1,1,1);`)).toThrow('service_quote_lines_quote_workspace_841');
 }),30000);
});
