import { describe,expect,it } from "bun:test";
import { readFileSync } from "node:fs";
import { withScratchPostgres,hasScratchPostgres } from "../../scripts/testing/scratch-postgres";
(hasScratchPostgres?describe:describe.skip)('authoritative report semantics',()=>{
 it('uses real WO duration, claimed cash and hours; separates posted margin; pages eligible invoices before limiting',()=>{
  withScratchPostgres(q=>{
   q(`create role authenticated;create role anon;create role service_role;create schema auth;
    create function auth.uid() returns uuid language sql stable as $$select '10000000-0000-0000-0000-000000000001'::uuid$$;
    create function auth.role() returns text language sql stable as $$select coalesce(nullif(current_setting('request.role',true),''),'authenticated')$$;
    create function get_my_workspace() returns text language sql stable as $$select 'w1'::text$$;
    create function service_can_view_metrics() returns boolean language sql as $$select true$$;
    create table crm_companies(id uuid primary key,name text);
    create table crm_contacts(id uuid primary key,first_name text,last_name text,phone text);
    create table crm_deal_stages(id uuid primary key,name text,sort_order integer,probability integer,is_closed_won boolean);
    create table crm_deals(id uuid primary key,workspace_id text default 'w1',company_id uuid,primary_contact_id uuid,stage_id uuid,amount numeric,name text,created_at timestamptz,updated_at timestamptz,expected_close_on date,last_activity_at timestamptz,next_follow_up_at timestamptz,deal_score numeric,deleted_at timestamptz,assigned_rep_id uuid,closed_at timestamptz);
    create table quote_packages(deal_id uuid,status text,workspace_id text default 'w1');
    create table customer_invoices(id uuid primary key default gen_random_uuid(),workspace_id text default 'w1',deal_id uuid,invoice_type text,reversal_of_invoice_id uuid);
    create table service_jobs(id uuid primary key,workspace_id text,request_type text,shop_or_field text,opened_at timestamptz,created_at timestamptz,closed_at timestamptz,deleted_at timestamptz);
    create table service_labor_ledger(service_job_id uuid,workspace_id text,customer_invoice_id uuid,labor_sale_cents bigint,labor_cost_cents bigint,labor_cost_rate_cents bigint,deleted_at timestamptz,billed_status text,service_timecard_id uuid,actual_hours numeric,labor_date date,created_at timestamptz);
    create table service_billing_rows(service_job_id uuid,workspace_id text,customer_invoice_id uuid,extended_price_cents bigint,extended_cost_cents bigint,unit_cost_cents bigint,deleted_at timestamptz,billed_status text,row_type text);
    create table service_timecards(service_job_id uuid,workspace_id text,hours numeric,clocked_in_at timestamptz);
    create table service_warranty_claims(workspace_id text,requested_amount_cents bigint,approved_amount_cents bigint,paid_amount_cents bigint,status text,submitted_at timestamptz,deleted_at timestamptz);`);
   q(readFileSync(new URL('./843_authoritative_reporting.sql',import.meta.url),'utf8'));
   q(`insert into crm_companies values('20000000-0000-0000-0000-000000000001','Customer');
    insert into crm_deal_stages values('30000000-0000-0000-0000-000000000001','Delivery Completed',7,30,true);
    insert into crm_deals(id,company_id,stage_id,name,updated_at,assigned_rep_id) select md5(n::text)::uuid,'20000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000001','Deal',now()-interval '300 days'+n*interval '1 day',auth.uid() from generate_series(1,201) n;
    insert into customer_invoices(deal_id,invoice_type) select md5(n::text)::uuid,'equipment' from generate_series(1,200) n;
    insert into quote_packages(deal_id,status) values(md5('201')::uuid,'accepted');
    insert into customer_invoices(deal_id,invoice_type,workspace_id) values(md5('201')::uuid,'equipment','w2');
    insert into quote_packages(deal_id,status,workspace_id) values(md5('unquotable1')::uuid,'accepted','w2');
    insert into crm_deals(id,company_id,stage_id,updated_at) select md5(('unquotable'||n)::text)::uuid,'20000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000001',now()-interval '400 days' from generate_series(1,60) n;`);
   expect(()=>q('select * from select_equipment_invoice_candidates(50);')).toThrow('Service role required');
   expect(q(`set request.role='service_role';select deal_id=md5('201')::uuid from select_equipment_invoice_candidates(50);`)).toContain('t');
   expect(q('select distinct stage_probability from v_rep_pipeline')).toBe('30');q('update crm_deal_stages set sort_order=999;');expect(q('select distinct stage_probability from v_rep_pipeline')).toBe('30');
   q(`insert into service_jobs values('40000000-0000-0000-0000-000000000001','w1','customer_repair','shop',now()-interval '2 days',now()-interval '2 days',now()-interval '1 day',null),('40000000-0000-0000-0000-000000000002','w1','field_service','field',now()-interval '8 days',now()-interval '8 days',now()-interval '2 days',null),('40000000-0000-0000-0000-000000000003','w2','customer_repair','field',now()-interval '200 days',now()-interval '200 days',now(),null);
    insert into service_labor_ledger values('40000000-0000-0000-0000-000000000001','w1',null,10000,4000,null,null,'billed',null,3,current_date,now());
    insert into service_billing_rows values('40000000-0000-0000-0000-000000000001','w1',null,5000,2000,null,null,'paid','parts');
    insert into service_timecards values('40000000-0000-0000-0000-000000000001','w1',2,now()),('40000000-0000-0000-0000-000000000002','w1',8,now());
    insert into service_warranty_claims values('w1',10000,10000,2500,'approved',now(),null),('w2',900000,900000,900000,'paid',now(),null);`);
   const metrics=JSON.parse(q('select service_owner_metrics();'));
   expect(metrics.owner_summary.avg_cycle_time_hours).toBe(84);
   expect(metrics.owner_summary.warranty_recovery_pct).toBe(25);
   expect(metrics.owner_summary.warranty_filed_count).toBe(1);
   expect(metrics.owner_summary.warranty_outstanding_cents).toBe(7500);
   expect(metrics.owner_summary.field_mix_pct).toBe(61.54);
   expect(metrics.margin_by_type[0].total_revenue).toBe(150);
   expect(metrics.margin_by_type[0].total_margin_amount).toBe(90);
   expect(metrics.cycle_by_type).toHaveLength(2);
   q('update service_labor_ledger set labor_cost_cents=0,labor_cost_rate_cents=null');const incomplete=JSON.parse(q('select service_owner_metrics()'));expect(incomplete.margin_by_type[0].margin_pct).toBeNull();expect(incomplete.margin_by_type[0].missing_cost_line_count).toBe(1);
   expect(()=>q("select service_owner_metrics('w2');")).toThrow('access denied');
  });
 },30000);
});
