import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { withScratchPostgres, hasScratchPostgres } from "../../scripts/testing/scratch-postgres";
const m791=readFileSync(new URL('./791_m3_ar_receipts_desk.sql',import.meta.url),'utf8');
const migration=readFileSync(new URL('./845_stripe_receipt_identity.sql',import.meta.url),'utf8');
const schema=`create role anon;create role authenticated;create role service_role;create schema auth;
create function auth.role() returns text language sql stable as $$select current_setting('request.role',true)$$;
create function auth.uid() returns uuid language sql stable as $$select null::uuid$$;
create function get_my_workspace() returns text language sql stable as $$select 'ws'::text$$;
create function get_my_role() returns text language sql stable as $$select 'owner'::text$$;
create function qep_finance_can_mutate() returns boolean language sql stable as $$select true$$;
create function qep_finance_can_read() returns boolean language sql stable as $$select true$$;
create function set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create table qrm_companies(id uuid primary key,workspace_id text);create table profiles(id uuid primary key);create table portal_customers(id uuid primary key);create table branches(id uuid primary key);
create table customer_invoices(id uuid primary key,workspace_id text not null,crm_company_id uuid references qrm_companies,invoice_number text,total numeric,amount_paid numeric,status text,paid_at timestamptz,payment_method text,payment_reference text,updated_at timestamptz,due_date date,unique(workspace_id,id));
create table portal_payment_intents(id uuid primary key,workspace_id text,company_id uuid references qrm_companies,invoice_id uuid references customer_invoices,amount_cents bigint,stripe_payment_intent_id text,metadata jsonb default '{}');
insert into qrm_companies values('20000000-0000-0000-0000-000000000001','ws'),('20000000-0000-0000-0000-000000000002','other');
insert into customer_invoices values('30000000-0000-0000-0000-000000000001','ws','20000000-0000-0000-0000-000000000001','INV-1',100,0,'sent',null,null,null,now(),current_date);
insert into portal_payment_intents values('40000000-0000-0000-0000-000000000001','ws','20000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000001',10000,'pi_1','{}');`;
const apply=`set request.role='service_role';select apply_stripe_invoice_receipt('40000000-0000-0000-0000-000000000001','pi_1',10000,'evt_1');`;
(hasScratchPostgres?describe:describe.skip)('immutable Stripe receipt',()=>{
 it('commits canonical receipt and invoice together, survives late intent failure plus full refund, and never reapplies',()=>withScratchPostgres(query=>{
  query(schema);query(m791);query(migration);query('update portal_payment_intents set receipt_protocol_version=1;');
  expect(query(apply)).toContain('"already_applied": false');
  query(`create function fail_intent_update() returns trigger language plpgsql as $$begin raise exception 'injected late intent failure';end$$;create trigger fail_intent_update before update on portal_payment_intents for each row execute function fail_intent_update();`);
  expect(()=>query(`update portal_payment_intents set metadata='{"invoice_payment_applied_at":"2026-09-06"}';`)).toThrow('injected late intent failure');
  query("update customer_invoices set amount_paid=0,status='sent',payment_reference='reviewed_full_refund';");
  expect(query(apply)).toContain('"already_applied": true');
  expect(query('select amount_paid from customer_invoices;')).toEndWith('0');
  expect(query('select count(*) from customer_payments;')).toEndWith('1');
  expect(query('select count(*) from customer_payment_applications;')).toEndWith('1');
  expect(()=>query("update customer_payments set amount=200;")).toThrow('immutable');
  expect(()=>query('delete from customer_payment_applications;')).toThrow('immutable');
  expect(()=>query('delete from customer_payments;')).toThrow('immutable');
  expect(()=>query(`set request.role='service_role';select apply_stripe_invoice_receipt('40000000-0000-0000-0000-000000000001','pi_1',20000,'evt_wrong');`)).toThrow('differs from intended amount');
 }),30000);
 it('rolls back invoice and receipt when provider binding fails, then retries once; legacy ambiguity blocks',()=>withScratchPostgres(query=>{
  query(schema);query(m791);query(migration);
  expect(()=>query(apply)).toThrow('Legacy provider receipt is ambiguous');
  query(`update portal_payment_intents set receipt_protocol_version=1;
    create function fail_provider_bind() returns trigger language plpgsql as $$begin if new.provider_name is not null then raise exception 'injected provider bind failure';end if;return new;end$$;
    create trigger fail_provider_bind before update on customer_payments for each row execute function fail_provider_bind();`);
  expect(()=>query(apply)).toThrow('injected provider bind failure');
  expect(query('select amount_paid from customer_invoices;')).toEndWith('0');expect(query('select count(*) from customer_payments;')).toEndWith('0');
  query('drop trigger fail_provider_bind on customer_payments;');query(apply);query(apply);
  expect(query('select count(*) from customer_payment_applications;')).toEndWith('1');
  query("update portal_payment_intents set workspace_id='other',company_id='20000000-0000-0000-0000-000000000002';");
  expect(()=>query(apply)).toThrow('receipt scope, invoice or amount conflict');
 }),30000);
});
