/** JSON shape stored in voice_captures.extracted_data — not generated by Supabase CLI. */

export type SignalConfidence = "high" | "medium" | "low" | "unknown";

export type ExtractedEvidenceSnippet = {
  field: string;
  quote: string;
  confidence: SignalConfidence;
};

export type ExtractedDealData = {
  record: {
    contactName: string | null;
    contactRole: string | null;
    companyName: string | null;
    companyType: string | null;
    decisionMakerStatus: string;
    preferredContactChannel: string;
    locationContext: string | null;
    additionalStakeholders: string[];
  };
  opportunity: {
    machineInterest: string | null;
    equipmentCategory: string | null;
    equipmentMake: string | null;
    equipmentModel: string | null;
    attachmentsDiscussed: string[];
    applicationUseCase: string | null;
    dealStage: string | null;
    intentLevel: string;
    urgencyLevel: string;
    timelineToBuy: string | null;
    financingInterest: string;
    newVsUsedPreference: string;
    tradeInLikelihood: string;
    budgetRange: string | null;
    budgetConfidence: string;
    competitorsMentioned: string[];
    keyConcerns: string | null;
    objections: string[];
    quoteReadiness: string;
    nextStep: string | null;
    nextStepDeadline: string | null;
    actionItems: string[];
    followUpDate: string | null;
  };
  operations: {
    branchRelevance: string | null;
    territorySignal: string | null;
    serviceOpportunity: boolean;
    partsOpportunity: boolean;
    rentalOpportunity: boolean;
    crossSellOpportunity: string[];
    existingFleetContext: string | null;
    replacementTrigger: string | null;
    availabilitySensitivity: string;
    uptimeSensitivity: string;
    jobsiteConditions: string[];
    operatorSkillLevel: string;
  };
  guidance: {
    customerSentiment: string;
    probabilitySignal: string;
    stalledRisk: string;
    buyerPersona: string;
    managerAttentionFlag: boolean;
    recommendedNextAction: string | null;
    recommendedFollowUpMode: string;
    summaryForRep: string | null;
    summaryForManager: string | null;
  };
  evidence: {
    snippets: ExtractedEvidenceSnippet[];
    confidence: Record<string, SignalConfidence>;
  };
};
